version: "3"
services:
  app:
    build: ./
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      PSQL_HOST: database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PORT: 3000
  # client:
  #   build: ./client
  #   image: react_client
  #   links:
  #     - app
  #   working_dir: /home/node/app/client
  #   volumes:
  #     - ./:/home/node/app
  #   ports:
  #     - 3001:3001
  #   command: npm run start
  #   env_file:
  #     - ./client/.env
  database:
    image: postgres:9.6.8-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '3030:5432'
volumes:
  database: