version: "3.9"
networks:
  ilumeo:
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - ilumeo

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
    networks:
      - ilumeo
